"""empty message

Revision ID: 0acdcb274ff3
Revises: 44abb1caf0ea
Create Date: 2025-11-04 22:02:58.527236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acdcb274ff3'
down_revision: Union[str, Sequence[str], None] = '44abb1caf0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('function_indicators')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function_indicators',
    sa.Column('function_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('indicator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], name=op.f('function_indicators_function_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], name=op.f('function_indicators_indicator_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('function_id', 'indicator_id', name=op.f('function_indicators_pkey'))
    )
    op.drop_table('levels')
    # ### end Alembic commands ###
