"""Added levels

Revision ID: 0ea2656b72d9
Revises: b1a97272a07c
Create Date: 2025-10-15 20:27:44.392936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea2656b72d9'
down_revision: Union[str, Sequence[str], None] = 'b1a97272a07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('modules', sa.Column('level_id', sa.Integer(), nullable=False))
    op.add_column('modules', sa.Column('value', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('modules_project_id_fkey'), 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.drop_column('modules', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.create_foreign_key(op.f('modules_project_id_fkey'), 'modules', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('modules', 'value')
    op.drop_column('modules', 'level_id')
    op.drop_table('levels')
    # ### end Alembic commands ###
