"""empty message

Revision ID: 25eb0b61172b
Revises: 2eb13d152dcb
Create Date: 2025-10-18 07:47:28.728780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25eb0b61172b'
down_revision: Union[str, Sequence[str], None] = '2eb13d152dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function_indicators',
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('function_id', 'indicator_id')
    )
    op.drop_constraint(op.f('functions_module_id_fkey'), 'functions', type_='foreignkey')
    op.drop_column('functions', 'module_id')
    op.drop_constraint(op.f('indicators_module_id_fkey'), 'indicators', type_='foreignkey')
    op.drop_column('indicators', 'module_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('indicators_module_id_fkey'), 'indicators', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.add_column('functions', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('functions_module_id_fkey'), 'functions', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_table('function_indicators')
    # ### end Alembic commands ###
