"""Added levels, funcs, funcinicators

Revision ID: 3ac07a946259
Revises: 0ea2656b72d9
Create Date: 2025-10-16 09:47:49.016520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac07a946259'
down_revision: Union[str, Sequence[str], None] = '0ea2656b72d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('type', sa.String(), nullable=False))
    op.add_column('modules', sa.Column('indicator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modules', 'indicators', ['indicator_id'], ['id'])
    op.drop_column('modules', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'indicator_id')
    op.drop_column('modules', 'type')
    # ### end Alembic commands ###
