"""Модули теперь для хранения значений идикаторов и после работы функций

Revision ID: 4fd960f4bfc5
Revises: 25eb0b61172b
Create Date: 2025-11-04 21:51:17.787557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd960f4bfc5'
down_revision: Union[str, Sequence[str], None] = '25eb0b61172b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('value', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('modules_level_id_fkey'), 'modules', type_='foreignkey')
    op.drop_constraint(op.f('modules_indicator_id_fkey'), 'modules', type_='foreignkey')
    op.drop_constraint(op.f('modules_function_id_fkey'), 'modules', type_='foreignkey')
    op.drop_column('modules', 'level_id')
    op.drop_column('modules', 'indicator_id')
    op.drop_column('modules', 'type')
    op.drop_column('modules', 'function_id')
    op.drop_column('modules', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('modules', sa.Column('function_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('modules', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('modules', sa.Column('indicator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('modules', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('modules_function_id_fkey'), 'modules', 'functions', ['function_id'], ['id'])
    op.create_foreign_key(op.f('modules_indicator_id_fkey'), 'modules', 'indicators', ['indicator_id'], ['id'])
    op.create_foreign_key(op.f('modules_level_id_fkey'), 'modules', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.drop_column('modules', 'value')
    # ### end Alembic commands ###
