"""исправлены модели для получения из запросов проекта всех модулей

Revision ID: cb9c97e42fc6
Revises: 0acdcb274ff3
Create Date: 2025-11-06 09:18:38.593500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9c97e42fc6'
down_revision: Union[str, Sequence[str], None] = '0acdcb274ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('level_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'functions', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.add_column('modules', sa.Column('level_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'modules', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'level_id')
    op.drop_constraint(None, 'functions', type_='foreignkey')
    op.drop_column('functions', 'level_id')
    # ### end Alembic commands ###
